#!/usr/bin/env bash
# Function to display subdomain information

dns_config() {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check if the domain exists
#if [ ! -z "$1" ] && [ -z "$2" ]; then
#    echo "Error: Domain name is required"
#    exit 1
#fi

# Check if the subdomain is provided
if [ -z "$2" ]; then
    dns_config "$1" "www"
    dns_config "$1" "lb-01"
    dns_config "$1" "web-01"
    dns_config "$1" "web-02"
else
    dns_config "$1" "$2"
fi
