#!/usr/bin/env bash
# Configuring SSL termination and certificates

frontend edzordzinam-tech-frontend
        bind *:80
        bind *:443 ssl crt /etc/letsencrypt/live/www.edzordzinam.tech
        http-request set-header X-Forwaded-Proto https
        default_backend my_backend

backend edzordzinam-tech-backend
        balance roundrobin
        server 477863-web-01 18.204.15.197:80 check
        server 477863-web-02 54.236.24.208:80 check
