#!/usr/bin/env bash
# Configuring SSL termination and certificates

frontend my_frontend
        bind *:80
        bind *:443 ssl crt /etc/letsencrypt/live/www.edzordzinam.tech/all.pem
        http-request set-header X-Forwaded-Proto https
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 477863-web-02 100.26.237.225:80 check
        server 477863-web-02 100.26.237.225:80 check
