#!/usr/bin/env bash
# A script that transfers files from a client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i	"$4" "$1" "$3"@"$2":~/
fi
