#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me#is redirecting to another page.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a blog post
sudo sed -i '24\	rewrite ^/redirect_me https://popsygyile.blogspot.com permanent;' /etc/nginx/sites--available/default

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
