#!/usr/bin/env bash
# Nginx redirection

sudo apt-get update -y

sudo apt-get install -y nginx

sudo tee /etc/nginx/sites-available/default >/dev/null <<EOF
server {
	listen 80;
	listen [::]:80;
	server_name 52.87.215.215;

	location /redirect_me {
		return 301 https://popsygyile.blogspot.com;
	}

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
}
EOF

sudo service nginx restart
